<?php

use App\Helper\MongoCollectionMigration;
use Illuminate\Support\Facades\Schema;

return new class extends MongoCollectionMigration
{
    /**
     * Collection name
     *
     * @var string
     */
    protected $collectionName = 'students';

    /**
     * Schema validator for students collection
     *
     * @var array
     */
    protected $schemaValidator = [
        '$jsonSchema' => [
            'bsonType' => 'object',
            'title' => 'Student Object Validation',
            'required' => ['name', 'year'],
            'properties' => [
                '_id' => [
                    'bsonType' => 'objectId',
                    'description' => "'_id' is automatically generated by MongoDB",
                ],
                'name' => [
                    'bsonType' => 'string',
                    'description' => "'name' must be a string and is required",
                ],
                'year' => [
                    'bsonType' => 'int',
                    'minimum' => 2017,
                    'maximum' => 3017,
                    'description' => "'year' must be an integer in [2017, 3017] and is required",
                ],
                'gpa' => [
                    'bsonType' => 'double',
                    'description' => "'gpa' must be a double if the field exists",
                ],
                'address' => [
                    'bsonType' => 'string',
                    'description' => "'address' must be a string and is required",
                ],
                'major' => [
                    'bsonType' => 'string',
                    'description' => "'major' must be a string and is required",
                ],
                'created_at' => [
                    'bsonType' => 'date',
                    'description' => "'created_at' is a timestamp",
                ],
                'updated_at' => [
                    'bsonType' => 'date',
                    'description' => "'updated_at' is a timestamp",
                ],
            ],
            'additionalProperties' => false,
        ],
    ];
};
